# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sikshauserprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sikshauserprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='sikshauserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sikshauserprofile',
            name='display_picture',
            field=models.ImageField(default='uploads/displaypictures/male-silhouette.jpg', upload_to='uploads/displaypictures'),
        ),
    ]
